# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Edzer Pebesma
email: edzer.pebesma@uni-muenster.de 
description: > # this means to ignore newlines until "baseurl:"
   An overview of some of my software projects, blogs, and pointers to other stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://edzer.github.io/" # the base hostname & protocol for your site
twitter_username: edzerpebesma
github_username:  edzer

# Build settings
markdown: kramdown
